CLD-3rd/Final-Team1-Backend

- mindscape-info/pom.xml
- mindscape-info/src/main/java/likelion/team1/mindscape/user/controller/UserController.java
- mindscape-info/src/main/java/likelion/team1/mindscape/user/dto/UserResponseDto.java
- mindscape-info/src/main/java/likelion/team1/mindscape/user/entity/User.java
- mindscape-info/src/main/java/likelion/team1/mindscape/user/repository/UserRepository.java
- mindscape-info/src/main/java/likelion/team1/mindscape/user/service/UserService.java
> feat: 유저 서비스 기능 추가

- mindscape-info/src/main/java/likelion/team1/mindscape/WebConfig.java
- mindscape-info/src/main/java/likelion/team1/mindscape/test/controller/TestController.java
- mindscape-info/src/main/java/likelion/team1/mindscape/test/dto/TestRequestDto.java
- mindscape-info/src/main/java/likelion/team1/mindscape/test/service/TestService.java
- mindscape-info/src/main/resources/application.properties
- 프론트엔드 연동
- 테스트 결과 DB 저장 구현 
- 요구사항 추가
> feat: 프론트엔드 연동, 테스트 결과 DB 저장 구현 및 요구사항 추가

- terraform/.terraform.lock.hcl
- terraform/main.tf
- terraform/modules/network/vpc/main.tf
- terraform/modules/network/vpc/outputs.tf
- terraform/modules/network/vpc/variables.tf
- terraform/outputs.tf
> feat: vpc 모듈 추가

- terraform/modules/iam/main.tf
> [fix]정책 수정3

- terraform/.terraform.lock.hcl
- terraform/modules/argocd/main.tf
- terraform/modules/argocd/variables.tf
- terraform/providers.tf
> fix: argocd 에러 해결

- terraform/modules/iam/main.tf
> [fix] oidc url 수정

- terraform/main.tf
- terraform/modules/namespace/main.tf
- terraform/modules/namespace/outputs.tf
- terraform/modules/namespace/variables.tf
- terraform/modules/namespace/versions.tf
> fix: 네임스페이스 모듈 관련 코드 주석 해제

- terraform/.terraform.lock.hcl
- terraform/modules/eks/main.tf
- terraform/modules/eks/outputs.tf
> [fix] oidc url eks에서 나오게 변경

- terraform/modules/argocd/main.tf
> [fix]rbac 추가

- terraform/main.tf
- terraform/modules/ebs-csi-driver/main.tf
- terraform/modules/ebs-csi-driver/outputs.tf
- terraform/modules/ebs-csi-driver/variables.tf
- terraform/modules/ebs-csi-driver/version.tf
- terraform/modules/irsa/ebs-csi-policy.json
- terraform/modules/irsa/main.tf
- terraform/modules/monitoring/prometheus/main.tf
- terraform/modules/monitoring/prometheus/values.yaml
- terraform/modules/storageclass/main.tf
- terraform/modules/storageclass/variables.tf
- terraform/providers.tf
> feat: ebs csi 드라이버 관련 정책 추가

- terraform/main.tf
- terraform/modules/ebs-csi-driver/main.tf
- terraform/modules/ebs-csi-driver/version.tf
- terraform/modules/irsa/main.tf
- terraform/modules/irsa/outputs.tf
> fix: ebs-csi-driver 프로바이더 문제 해결

- terraform/main.tf
- terraform/modules/ebs-csi-driver/main.tf
- ebs-csi-driver sa 생성 하도록 변경 및 테라폼 클라우드 로컬 연결 코드 추가
> fix: ebs-csi-driver sa 생성 하도록 변경 및 테라폼 클라우드 로컬 연결 코드 추가

- terraform/main.tf
- terraform/modules/storageclass/main.tf
- terraform/modules/storageclass/versions.tf
> fix;스토리지 클래스프로바이더 수정

- argocd/manifests/ingress/app/ingress.yaml
> feat: app ingress 야믈 작성

- terraform/main.tf
- terraform/modules/karpenter/crd-install.tf
- terraform/modules/karpenter/main.tf
- terraform/modules/karpenter/tagging.tf
> [fix[ crd-install 수정 

- terraform/modules/karpenter/main.tf
>  [fix] sts 문제 해결

- terraform/main.tf
- terraform/modules/karpenter/main.tf
- terraform/modules/karpenter/node_resources.tf
- terraform/modules/monitoring/grafana/outputs.tf
- terraform/modules/monitoring/prometheus/outputs.tf
- terraform/providers.tf
> [fix]provider kubectl.bastion 추가

- terraform/main.tf
- terraform/modules/karpenter/ec2nodeclass.yaml.tpl
- terraform/modules/karpenter/main.tf
- terraform/modules/karpenter/node_resources.tf
- terraform/modules/karpenter/nodepool.yaml.tpl
- terraform/modules/karpenter/rbac.tf
- terraform/modules/karpenter/variables.tf
- terraform/modules/security-group/main.tf
- terraform/modules/security-group/variables.tf
> [fix] namespace 생성

- terraform/main.tf
- terraform/modules/karpenter/ec2nodeclass.yaml.tpl
- terraform/modules/karpenter/main.tf
- terraform/modules/karpenter/nodepool.yaml.tpl
- terraform/modules/karpenter/variables.tf
> [fix]namespace 삭제

- terraform/main.tf
- terraform/modules/bastion/main.tf
- terraform/modules/bastion/variables.tf
- terraform/modules/iam/outputs.tf
> [fix]bastion main.tf

- terraform/main.tf
- terraform/modules/argocd/main.tf
- terraform/modules/argocd/variables.tf
- terraform/modules/karpenter/ec2nodeclass.yaml.tpl
- terraform/modules/monitoring/grafana/main.tf
- terraform/modules/monitoring/grafana/outputs.tf
- terraform/modules/monitoring/grafana/variables.tf
- terraform/modules/monitoring/prometheus/main.tf
- terraform/modules/monitoring/prometheus/outputs.tf
- terraform/modules/monitoring/prometheus/variables.tf
> [fix] 주석 해제

- terraform/main.tf
- terraform/modules/karpenter/ec2nodeclass.yaml.tpl
- terraform/modules/karpenter/node_resources.tf
- terraform/modules/network/subnet/main.tf
- terraform/modules/network/subnet/variables.tf
- ec2nodeclass.yaml 완성본
- subnet tag 추가
> [fix]ec2nodeclass.yaml

- terraform/main.tf
- terraform/modules/argocd/main.tf
- terraform/modules/argocd/variables.tf
- terraform/modules/monitoring/grafana/main.tf
- terraform/modules/monitoring/grafana/outputs.tf
- terraform/modules/monitoring/grafana/variables.tf
- terraform/modules/monitoring/prometheus/main.tf
- terraform/modules/monitoring/prometheus/outputs.tf
- terraform/modules/monitoring/prometheus/variables.tf
> [fix] 주석 활성화

- terraform/main.tf
- terraform/modules/argocd/main.tf
- terraform/modules/argocd/variables.tf
- terraform/modules/monitoring/grafana/main.tf
- terraform/modules/monitoring/grafana/outputs.tf
- terraform/modules/monitoring/grafana/variables.tf
- terraform/modules/monitoring/prometheus/main.tf
- terraform/modules/monitoring/prometheus/outputs.tf
- terraform/modules/monitoring/prometheus/variables.tf
> [fix] 주석 해제(argocd, 프로, 그라파나)

- mindscape-info/src/main/java/likelion/team1/mindscape/test/controller/TestController.java
- mindscape-info/src/main/java/likelion/team1/mindscape/test/repository/TestRepository.java
- mindscape-info/src/main/java/likelion/team1/mindscape/test/service/TestService.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/client/TestServiceClient.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/controller/ResponseController.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/dto/ContentCountDto.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/repository/BookRepository.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/repository/MovieRepository.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/repository/MusicRepository.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/service/ResponseService.java
> feat(ranking): add ranking feature - Change info service to support paging feature

- .idea/Final-Team1-Backend-dev 2.iml
- .idea/compiler.xml
- .idea/encodings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- mindscape-auth/pom.xml
- mindscape-info/src/main/java/likelion/team1/mindscape/test/controller/TestController.java
- mindscape-info/src/main/java/likelion/team1/mindscape/test/service/TestService.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/controller/ContentController.java
- mindscape-service/src/main/java/likelion/team1/mindscape/content/enums/ContentType.java
- 검색 기능 구현
영화
`http://localhost:8080/api/content/search?content=MOVIE&query=[영화제목]`
음악
`http://localhost:8080/api/content/search?content=MUSIC&artist=[가수명]&title=[노래제목]`
책
`http://localhost:8080/api/content/search?content=BOOK&title=[책제목]`
> [Feat] 검색 기능 구현
